In [2]:
import numpy as np

In [3]:
np.random.randint(1,100,30)

array([32, 68, 53, 48, 24, 75, 40, 23, 89, 27, 37, 62, 89, 75, 98, 75, 55,
       41, 34, 34, 86, 74, 28, 62, 89, 10, 83, 87, 11, 28])

In [4]:
arr = np.arange(25)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
arr[4]

4

In [7]:
arr[:5]
#arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [9]:
arr[4:22]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21])

In [10]:
arr_copy = arr.copy()
#it makes a copy of an array in memor in order to keep original array

In [11]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arr[0:10] = 99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
arr2d = np.array([[10,15],[20,25],[30,35]])
# for defining a 1d array we use single paranthesis and for 2d array we use double paranthesis

In [16]:
arr2d

array([[10, 15],
       [20, 25],
       [30, 35]])

In [17]:
arr2d[1]

array([20, 25])

In [18]:
#arr2d[1][1]
arr2d[1,1]

25

In [19]:
arr2d[1:2,0:]
#THIS WILL grab elements from row at index 1 and elements at indces 0 an 1

array([[20, 25]])

In [20]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.shape

(25,)

In [22]:
arra = np.zeros((10,10))

In [23]:
arra

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
arra.shape

(10, 10)

In [25]:
arra_length1  = arra.shape[1]
arra_length1

10

In [26]:
for i in range(arra_length1):
    arra[i] = i

In [27]:
arra

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [28]:
#arra_length = arra.shape[0]

In [29]:
#arra_length

In [30]:
#for i in range(arra_length):
 #   arra[i] = 10

In [31]:
#arra

In [32]:
arra[[0,1,3]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [33]:
arra[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [34]:
arr_2d = np.array([[10,15,20],[25,30,35],[40,45,50]])

In [35]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [36]:
arr_1 = np.arange(1,11)

In [37]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_1 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
bool_arr = arr_1 > 5

In [40]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr_1[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr_1[arr_1 > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
x = 2
arr_1[arr_1 > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Numpy operation 

In [44]:
ar = np.arange(0,10)

In [45]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
ar - ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
ar * ar

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
ar/ar

C:\Users\Jawwad Ali\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
ar**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [51]:
ar**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Universal array function

In [52]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [53]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [54]:
np.max(ar)

9

In [55]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [56]:
np.log(ar)

C:\Users\Jawwad Ali\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [57]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [61]:
arr_2d.sum()

270

In [62]:
arr_2d.sum(axis=0)

array([ 75,  90, 105])

In [63]:
arr_2d.sum(axis=1)

array([ 45,  90, 135])

In [59]:
arr_2d.std()

12.909944487358056

In [ ]:
arr_2d